[phases.setup]
nixPkgs = ["python311", "gcc", "g++"]

[phases.install]
cmds = [
  "python3.11 -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate && pip install --upgrade pip setuptools wheel",
  ". /opt/venv/bin/activate && pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "uvicorn app.server:app --host 0.0.0.0 --port $PORT"
